coblox/nectar

- src/bitcoind.rs
- src/ongoing_swaps.rs
- src/swap.rs
The function can be used by both parties, ensuring that the execution of a swap cannot get out of sync.
The function is generic over actors which have to implement certain actions. In `WalletACTOR` implementations, a wallet is used to actually peform the action; in `WatchOnlyACTOR` implementations, `btsieve` is used to monitor the blockchain.
Temporary `BitcoinWallet` and `EthereumWallet` dummy types are introduced to satisfy the compiler. They will eventually be replaced by traits implemented by wallets (such as the ones which will actually power Nectar).
---
Opened PR as an FYI and in order to move the state of master forward. I already got feedback whilst working on it. Nevertheless, feel free to leave comments.
> Defined single hbit_herc20 function for Alice and Bob

- Cargo.lock
- Cargo.toml
- src/bitcoin.rs
- src/dai.rs
- src/float_maths.rs
- src/lib.rs
- src/main.rs
- src/publish.rs
- src/rate.rs
Remove any calculation that relies on floating point representation of a number.
I attempted to provide comments to explain what is going on. Feel free to claim more explanations/clarifications.
Everything that looks like it could panic or overflow is property tested, let me know if I missed something.
I also attempted to be smart in the usage of the primitives, do not hesitate to ask why a given primitive is used where.
Finally, `dai::Amount::from_dai` takes a `f64` input. I am not sure this is the right choice and I hesitated to just accept a string slice. Let me know your thoughts.
> Remove float arithmetic

- Cargo.toml
- src/swap.rs
I'm happy to move forward with this simpler design. Let me know if the logic is sound.
I'm not sure how this new design would fit in with two watch-only actors (cnd's use-case), but I think it's okay for Nectar.
> Allow and prioritise refund during swap execution

- src/bitcoin.rs
- src/bitcoin_wallet.rs
I left the bitcoind impl to use the bitcoin library's Amount because that seems cleaner.
Did not see this problem tackled yet in another PR so I thought I create a quick patch. Feel free to close and link to other PR if we already tackle this.
> Return our own bitcoin Amount as wallet balance

- Cargo.lock
- src/main.rs
- src/maker.rs
- src/mid_market_rate.rs
- src/order.rs
First commit is the (simple) rate update logic. 
The second commit shows an approach to deal with failed rate updates by comparing against the timestamp of the MidMarketRate. 
Since this is unnecessary complicated I opted for changing the `mid_market_rate` of `Maker` to be an `Option` in the third commit. When we cannot find a rate we set it to `None`. 
The `timestamp` of `MidMarketRate` was removed as we don't need it for this logic. Note that I still kept the `MidMarketRate` struct, but it is now actually just a wrapper for the inner `Rate`. We could remove it.
> Maker rate update logic

- Cargo.lock
- Cargo.toml
- proptest-regressions/order.txt
- src/bitcoin.rs
- src/dai.rs
- src/main.rs
- src/maker.rs
- src/ongoing_takers.rs
- src/order.rs
Free funds and "remove taker from ongoing takers" logic.
This includes an update for the event loop model that allows us to process network events, swap execution events and balance/rate updates separately using `futures::select!`.
I would try to get this merged so that the new structure is in. Want to avoid rebasing this too often 😬
> Event loop optimisation and unreserving funds logic

- src/bitcoin_wallet.rs
- src/main.rs
- src/swap.rs
We can see that the API was not used correctly in the main indicating
it is not the best API.
Initialisation of the wallet in bitcoind is now done when instantiating
the wallet.
> Merge bitcoin wallet `new` and `init` methods

- src/bitcoin.rs
- src/dai.rs
- src/lib.rs
- src/main.rs
- src/maker.rs
- src/order.rs
First Commit: More complex logic, that takes the max-amount into account.
After sleeping over this on the weekend I feel it is unnecessarily complex at the moment.
I think it is totally fine to publish orders upon every balance change, even if that means "spamming" the network if the order's amounts did not change.
> Balance update logic

- Cargo.lock
To prevent breaking this dependency in the future:
- No more force pushing to `comit-rs/nectar`.
- Use path dependency or a separate branch if you need to make changes to `comit-rs/nectar`.
- Once the corresponding Nectar PR is approved, update `comit-rs/nectar` with the changes, run `cargo update -p comit` to update the dependency on the PR branch and go ahead with merging the PR.
> Depend on definitely stable version of COMIT lib

- Cargo.toml
- src/bitcoin/bitcoind.rs
- src/bitcoin/wallet.rs
- src/config/seed.rs
- src/ethereum/wallet.rs
- src/network.rs
- src/seed.rs
- src/swap.rs
- src/test_harness/bitcoin.rs
This is done the same manner than bitcoind does. Which means
that the seed can later be imported directly in bitcoind for
recovery purposes.
A test is done to prove it.
> Generate the Bitcoin root extended private key from the seed

- src/bitcoin/wallet.rs
- src/ethereum/geth.rs
- src/ethereum/wallet.rs
- src/swap.rs
- src/swap/ethereum.rs
- src/test_harness/ethereum.rs
We used to hard-code the gas price of transactions to 0 because it worked for a local development node (as proven by the swap execution integration test passing before these changes). Obviously, this wouldn't work in the real world. Using `eth_gasPrice` we ask the Ethereum node to give us a gas price that should be good enough.
This caused the swap execution integration test to fail, which was fixed by minting ether for Alice and Bob.
> Ask Ethereum node for gas price

- src/ethereum/geth.rs
- src/ethereum/wallet.rs
- src/test_harness/ethereum.rs
- Introduce ethereum::Wallet::gas_limit to do so.
- Remove unused geth::send_transaction. We always sign the transaction
locally and broadcast a raw transaction.
> Ask node for gas limit estimate for Wallet::send_transaction

- src/command/trade.rs
- src/maker.rs
- src/network.rs
Given that we only free funds once the swap execution is over, we need to make sure that we always reserve funds before respawning (since the `Maker`'s state is lost between restarts of Nectar).
Additionally, we could examine swaps and decide whether we have enough money or not to continue with the execution successfully, but it would be quite complex. Instead, we let the swap execution fail, which is functionally equivalent to preventing the respawn.
---
There is a second patch which makes it so that `deny` doesn't try to remove the order's taker from the set of `ActiveTaker`s, as @da-kami  correctly suggested in his review of PR #59.
> Reserve funds before respawn

- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
- src/bitcoin.rs
- src/bitcoin/amount.rs
- src/command/trade.rs
- src/ethereum/dai.rs
- src/maker.rs
- src/network.rs
- src/order.rs
- src/rate.rs
- src/swap.rs
- src/swap/alice.rs
- src/swap/bitcoin.rs
- src/swap/bob.rs
- src/swap/ethereum.rs
This allows us to support both buy and sell orders!
It also allows us to set expiries properly when creating orders.
We add missing implementations to enable calling `nectar_herc20_hbit`.
The main limitation now is that orders are still limited to a local development network. This should be easy to fix once we include the network as part of the `dai::Asset` and a possible `nectar::bitcoin::Asset`.
> Upgrade to latest version of COMIT lib

- src/ethereum/dai.rs
- src/maker.rs
- src/order.rs
The rate is always the same, no matter the position so when we want
to convert from quote to base (dai to btc) we needed to divide by the
rate, not multiply.
> Invert the rate

- src/bitcoin/wallet.rs
- src/command/wallet_info.rs
- src/ethereum/wallet.rs
- src/main.rs
- src/seed.rs
Allow `nectar wallet-info` to print even if no blockchain nodes are reachable.
> More resilient `wallet-info`

- src/swap/alice.rs
- src/swap/bitcoin.rs
- src/swap/ethereum.rs
Ensure that we always check that the contract has expired before executing the refund action.
> Align hbit::ExecuteRefund impls with herc20::ExecuteRefund impls

- .github/workflows/ci.yml
- src/maker.rs
- src/network.rs
- src/order.rs
Minimal printing of the order position and nominal values.
I think this is actually so basic that it is fine to add. We can also drop it, but I feel a bit more context would be good when running `trade`. (I also thought about printing the `Rate` and `Balance` but did not go there yet...)
```
Jul 22 15:50:15.919  INFO nectar::trace: Initialized tracing with level: INFO
Jul 22 15:50:15.923  INFO nectar::config::seed: Read in seed from file: /Users/dakami/Library/Application Support/nectar/seed.pem
Jul 22 15:50:16.471  INFO libp2p_gossipsub::behaviour: Subscribed to topic: BTC/DAI    
Jul 22 15:50:16.472  INFO nectar::maker: New order created: Position: Sell, BTC: 0.09990725, DAI: 967.83
Jul 22 15:50:16.472  INFO nectar::maker: New order created: Position: Buy, BTC: 175294, DAI: 20
Jul 22 …
```
> Print newly created orders

- Cargo.lock
- Cargo.toml
Hoping to fix the `can't find crate for `serde_derive` which `bitcoin`
depends on` error thanks to comit-network/comit-rs#b1315f28a4073b6aaf35a55bcb13109c2f8f0264
> Upgrade comit-rs

- README.md
- sample-config.toml
- src/command.rs
- src/config.rs
- src/config/file.rs
Use a sample toml config file instead of embedded in markdown.
Parse and check the result as part of the tests.
> Improve config documentation

- src/bitcoin/amount.rs
- src/ethereum.rs
- src/history.rs
- src/main.rs
- src/maker.rs
- src/mid_market_rate.rs
- src/network.rs
- src/order.rs
- src/swap.rs
- src/swap/db.rs
- src/swap/db/hbit.rs
- src/swap/db/herc20.rs
- src/test_harness.rs
So it's clearer whether we are using a stub or a
default value.
> Replace `Default` impl with `StaticStub`

- Cargo.lock
- Cargo.toml
- src/arbitrary.rs
- src/command/resume_only.rs
- src/command/trade.rs
- src/main.rs
- src/network.rs
- src/swap.rs
- src/swap/db.rs
- src/swap/db/hbit.rs
- src/swap/db/herc20.rs
- src/swap/hbit.rs
- src/swap_id.rs
Few things on the DB:
- Quickcheck tests
- Store values in CBOR instead of JSON: The main reason is that it's a binary format because the DB stores byte arrays. It made less sense to use JSON than CBOR but there is little different considering the usecase.
- flush the db when storing a swap (arguably the most import patch of the PR)
> Database improvements

- src/config.rs
- src/main.rs
I found a small bug when loading the config from the default location.
`ok_or_else` was used which essentially mapped to `Result<PathBuf, Error(Result<Path, Error>))`
Which resulted in the following behavior: 
if nectar was started with `-c /default/path/to/config/"` it would return Ok("/default/path/to/config/"). 
However, if the config param was left away, the mapping function would result in `Err(Ok("/default/path/to/config/")). 
At the end you were calling `ok()` on that result which mapped `Err(...)` to `Option::None` and hence always defaulting to the default config. 
Sorry for not providing a test and maybe there is also a neater way to solve this than using `map_or_else` which would get rid of the `to_path` mapping :)
> Fix default-config loading bug.

- .github/workflows/ci.yml
To avoid the `serde_derive` not found error.
> Deactivate caching of target dir on macos

- src/bitcoin/bitcoind.rs
- src/bitcoin/wallet.rs
- src/test_harness/bitcoin.rs
When funding the deposit address prior to creating the wallet the funding is not picked up. 
Adding `rescan` fixes this.
> Wallet rescan to pick up funding that happened prior to creating the wallet

- src/network.rs
Somehow we overlooked changing the code in the production code 😅
When testing the execution together with the TakerUI we ran into the problem that Nectar only spawns `HbitHerc20` swaps.
> Add decision which swap to spawn based on position to production code

- src/bitcoin/wallet.rs
- src/command/trade.rs
- src/network.rs
Instead of carrying around the root seed that is used to initialised
the crypto wallets, we used a `network::Seed` for network purposes.
The aim here is to protect the wallet seed from any bug in the network
module that would leak it.
It also removes the indirection of getting the seed via the Bitcoin
wallet.
> Introduce seed for network purposes

- Cargo.lock
- Cargo.toml
- src/bitcoin.rs
- src/bitcoin/amount.rs
- src/command/resume_only.rs
- src/command/trade.rs
- src/config/validation.rs
- src/ethereum/dai.rs
- src/maker.rs
- src/network.rs
- src/order.rs
- src/rate.rs
- src/swap.rs
- src/swap/bitcoin.rs
- src/swap/comit/hbit.rs
- src/swap/db/hbit.rs
The overall goal of this commit is bring nectar up to date with commit and reduce type duplication. Changed the BtcDaiOrderForm struct to use the price quantity model that was recently adopted by comit-rs. The bitcoin and dai asset types were removed because the btc and eth networks were no longer required. The PRECISION constant was fixed which was causing a 1 decimal place conversion error.
> Switch to Price/Quantity model
